services:
  _defaults:
    autowire: true
    autoconfigure: true

  DarkSidePro\SyliusFacebookFeedPlugin\Exporter\FacebookFeedExporterInterface: '@DarkSidePro\SyliusFacebookFeedPlugin\Exporter\XmlFacebookFeedExporter'
  
  DarkSidePro\SyliusFacebookFeedPlugin\Services\FeedGeneratorInterface: '@DarkSidePro\SyliusFacebookFeedPlugin\Services\ProductFeedGenerator'
  
  DarkSidePro\SyliusFacebookFeedPlugin\Command\GenerateFacebookFeedCommand:
    tags: ['console.command']